export const angularQuestions: Record<string, readonly string[]> = {
  'Componentes, templates e data binding': [
    'Como funciona interpolation, property e event binding?',
    'Qual a diferença entre template-driven e reativo na prática?',
    'Como comunicar componente pai e filho com @Input/@Output?',
    'O que são pipes e quando usar?',
    'Como estruturar um componente Angular escalável?',
    'O que é ng-content e projeção de conteúdo?',
    'Como usar ngClass e ngStyle com critérios?',
    'Lifecycle hooks: OnInit vs OnDestroy na prática?',
  ],
  'Services, DI e RxJS': [
    'O que é injeção de dependência no Angular?',
    'Quando criar um Service separado do componente?',
    'Como usar Observable vs Promise em uma API?',
    'O que são operators map e switchMap com exemplo?',
    'Como evitar memory leak com subscriptions?',
    'providedIn root vs module: qual usar?',
    'Como usar shareReplay para cache de HTTP?',
    'Subject vs BehaviorSubject: diferença prática?',
  ],
  'Roteamento (Router) e guards': [
    'Como definir rotas lazy-loaded no Angular?',
    'Qual a diferença entre CanActivate e CanMatch?',
    'Como passar dados entre rotas com resolvers?',
    'Como criar rotas filhas em um layout com sidebar?',
    'Como redirecionar usuário não autenticado?',
    'RouterOutlet nomeado: quando usar?',
    'Como ler query params e fragment na rota?',
    'PreloadAllModules: vale a pena no seu app?',
  ],
  'Formulários reativos e validação': [
    'Como montar um FormGroup com validações síncronas?',
    'Como validar campos dependentes (ex.: confirmar senha)?',
    'Como exibir mensagens de erro por campo?',
    'Quando usar FormArray em formulários dinâmicos?',
    'Como testar um formulário reativo?',
    'Validators customizados: como criar?',
    'valueChanges e debounceTime: exemplo prático?',
    'Como desabilitar submit até o form ser válido?',
  ],
  'Signals, change detection e performance': [
    'O que são signals e como diferem de BehaviorSubject?',
    'Como funciona change detection Default vs OnPush?',
    'Quando usar trackBy em *ngFor?',
    'Como detectar gargalos de performance no Angular?',
    'Me dê um exemplo de componente OnPush otimizado.',
    'computed() e effect(): quando usar cada um?',
    'Como migrar de RxJS para signals gradualmente?',
    'RunOutsideAngular: em que cenário usar?',
  ],
  'NgRx e estado reativo': [
    'Store, Actions, Reducers e Effects: papel de cada um?',
    'Quando NgRx vale a pena vs Service + BehaviorSubject?',
    'Como criar uma feature store completa?',
    'Como selecionar dados com selectors memoizados?',
    'Como tratar erro e loading no Effect?',
    'EntityAdapter: quando usar para listas?',
    'DevTools do NgRx: como debugar fluxo?',
    'Como testar reducer e effects isoladamente?',
  ],
  'HTTP Client e interceptors': [
    'Como fazer GET e POST com HttpClient?',
    'Como tipar resposta de API com generics?',
    'Interceptor para JWT: passo a passo?',
    'Como tratar erro 401 globalmente?',
    'Retry e timeout em requisições HTTP?',
    'Como mockar HttpClient em testes?',
    'Upload de arquivo com progresso: como fazer?',
    'Base URL por ambiente: boas práticas?',
  ],
  'Testes unitários e de componente': [
    'TestBed.configureTestingModule: o que configurar?',
    'Como testar componente com @Input dinâmico?',
    'Como mockar Service injetado?',
    'fixture.detectChanges(): quando chamar?',
    'Como testar Observable com fakeAsync?',
    'Como testar RouterLink e navegação?',
    'Cobertura mínima útil em projeto Angular?',
    'Jest vs Karma no Angular moderno?',
  ],
  'Standalone components (Angular moderno)': [
    'O que muda sem NgModule no dia a dia?',
    'Como importar CommonModule e Router em standalone?',
    'bootstrapApplication vs platformBrowserDynamic?',
    'Como migrar um módulo legado para standalone?',
    'provideRouter e provideHttpClient: setup mínimo?',
    'Lazy load de standalone routes: como?',
    'Quando ainda usar NgModule em 2025?',
    'Como organizar pastas em app standalone?',
  ],
  'Internacionalização (i18n)': [
    'Como configurar i18n no angular.json?',
    'Como marcar textos no template para tradução?',
    'Como trocar idioma em runtime?',
    'Plural e gênero em mensagens i18n?',
    'Como traduzir strings no TypeScript?',
    'Datas e números por locale: como formatar?',
    'Lazy loading de arquivos de idioma?',
    'Testes com múltiplos locales?',
  ],
};
