export const flutterQuestions: Record<string, readonly string[]> = {
  'Widgets (Stateless vs Stateful)': [
    'Qual a diferença entre StatelessWidget e StatefulWidget?',
    'Quando chamar setState e o que ele faz?',
    'Como extrair widgets para melhorar legibilidade?',
    'O que é const constructor e por que usar?',
    'Como organizar widgets em pastas/features?',
    'Key: quando usar ValueKey e ObjectKey?',
    'InheritedWidget: conceito e uso básico?',
    'Como evitar rebuild desnecessário na árvore?',
  ],
  'Layout (Row, Column, Stack, ListView)': [
    'Como centralizar um widget na tela?',
    'Qual a diferença entre Expanded e Flexible?',
    'Quando usar Stack em vez de Column?',
    'ListView.builder vs ListView: quando usar cada um?',
    'Como criar um layout responsivo simples?',
    'Padding vs SizedBox vs Container: quando usar?',
    'Como usar MediaQuery para breakpoints?',
    'Slivers e CustomScrollView: visão geral?',
  ],
  'Gerenciamento de estado (setState, Provider)': [
    'Quando setState é suficiente?',
    'Como o Provider injeta estado na árvore?',
    'Como separar UI de lógica de estado?',
    'Riverpod ou Provider: qual começar?',
    'Me mostre um contador e depois uma lista com estado.',
    'ChangeNotifier: como notificar listeners?',
    'Consumer vs Provider.of: diferença?',
    'Como testar lógica de estado isolada?',
  ],
  'Navegação e rotas': [
    'Como configurar rotas com go_router?',
    'Como passar argumentos entre telas?',
    'Como implementar bottom navigation?',
    'Como voltar e limpar pilha de navegação?',
    'Deep link: como funciona na prática?',
    'Redirect e guards no go_router?',
    'ShellRoute para layout com abas?',
    'Como passar objeto complexo entre rotas?',
  ],
  'Async, Futures e integração com APIs': [
    'Qual a diferença entre Future e Stream?',
    'Como usar async/await com FutureBuilder?',
    'Como tratar erro e loading em uma chamada HTTP?',
    'Onde colocar chamadas de API na arquitetura?',
    'Como parsear JSON para modelos Dart?',
    'dio vs http package: qual escolher?',
    'Como cancelar requisição ao sair da tela?',
    'Refresh token: fluxo com interceptor?',
  ],
  'Animações e transições': [
    'AnimationController vs AnimatedBuilder?',
    'Como animar opacidade e tamanho?',
    'Hero animation entre telas: exemplo?',
    'Curves: easeInOut vs bounce quando usar?',
    'ImplicitlyAnimatedWidget: casos de uso?',
    'Como animar lista ao inserir item?',
    'Lottie no Flutter: como integrar?',
    'Performance: evitar rebuild em animação?',
  ],
  'Temas, Material e Cupertino': [
    'ThemeData: como definir cores e tipografia globais?',
    'Dark mode: como alternar tema?',
    'Material 3 no Flutter: o que mudou?',
    'Quando usar widgets Cupertino no iOS?',
    'Como criar ThemeExtension customizado?',
    'TextTheme e fontes customizadas?',
    'Como aplicar tema só em uma subtree?',
    'Acessibilidade de contraste no Theme?',
  ],
  'Persistência local (SharedPreferences)': [
    'SharedPreferences: o que guardar e o que evitar?',
    'Como salvar token ou preferências do usuário?',
    'Hive vs sqflite: quando usar cada um?',
    'Como serializar objeto para storage?',
    'Como criptografar dados sensíveis localmente?',
    'Como limpar cache ao logout?',
    'path_provider: onde ficam os arquivos?',
    'Offline-first: estratégia básica?',
  ],
  'Testes de widget e integração': [
    'testWidgets: estrutura de um teste básico?',
    'Como encontrar widget por Key e texto?',
    'Como simular tap e scroll em teste?',
    'Como mockar Provider em teste de widget?',
    'golden tests: quando vale a pena?',
    'integration_test: diferença para widget test?',
    'Como rodar testes no CI?',
    'Cobertura útil em app Flutter?',
  ],
  'Build e publicação (Android/iOS)': [
    'Como gerar APK e App Bundle release?',
    'Assinatura Android: keystore passo a passo?',
    'Como configurar ícone e splash nativos?',
    'Build iOS: requisitos no Mac?',
    'version e buildNumber no pubspec?',
    'Flavors/dev/prod: como separar ambientes?',
    'O que revisar antes de publicar na loja?',
    'Crashlytics e analytics: visão geral?',
  ],
};
