export const jsQuestions: Record<string, readonly string[]> = {
  'Tipos, variáveis e escopo (let, const)': [
    'Qual a diferença entre var, let e const?',
    'O que é hoisting e como evitar bugs?',
    'Como funcionam tipos primitivos vs objetos?',
    'O que é escopo de bloco com exemplo?',
    'Como usar strict mode e por quê?',
    '== vs ===: por que sempre usar ===?',
    'Truthy e falsy: exemplos que pegam em entrevista?',
    'Temporal dead zone com let/const?',
  ],
  'Funções, arrow functions e closures': [
    'Qual a diferença entre function e arrow function?',
    'O que é closure com um exemplo real?',
    'Como o this muda em arrow vs function normal?',
    'O que são higher-order functions?',
    'Como usar callback sem callback hell?',
    'bind, call e apply: diferença prática?',
    'Currying: o que é e para que serve?',
    'Recursão: quando usar e risco de stack overflow?',
  ],
  'Arrays, objetos e métodos modernos (map, filter)': [
    'Quando usar map vs forEach?',
    'Como clonar objeto sem mutar o original?',
    'Como desestruturar array e objeto?',
    'filter + reduce: exemplo de soma de valores',
    'Como evitar mutação acidental em arrays?',
    'flatMap e findLast: casos de uso?',
    'Optional chaining (?.) e nullish (??)?',
    'Object.keys vs Object.entries: quando usar?',
  ],
  'Promises, async/await e fetch': [
    'Qual a diferença entre Promise e async/await?',
    'Como tratar erro com try/catch em async?',
    'Como fazer duas requisições em paralelo?',
    'O que é Promise.all e quando usar?',
    'Me mostre fetch com loading e mensagem de erro.',
    'Promise.race e Promise.allSettled: exemplos?',
    'Como cancelar fetch com AbortController?',
    'Retry automático em falha de rede?',
  ],
  'ES Modules, classes e padrões de código': [
    'Como import/export funciona em ES Modules?',
    'Quando usar class vs factory function?',
    'O que é destructuring em parâmetros de função?',
    'Como organizar pastas em um projeto JS moderno?',
    'Quais padrões ajudam código limpo no dia a dia?',
    'Default export vs named export: boas práticas?',
    'Barrel file (index.js): quando ajuda ou atrapalha?',
    'SOLID aplicado a JS: exemplo simples?',
  ],
  'DOM, eventos e manipulação da página': [
    'Como selecionar elementos (querySelector)?',
    'Event bubbling e capturing: diferença?',
    'Como delegar eventos em lista dinâmica?',
    'preventDefault vs stopPropagation?',
    'Como criar e remover elementos do DOM?',
    'Form submit sem recarregar página?',
    'localStorage vs sessionStorage?',
    'Por que manipular DOM direto pode ser lento?',
  ],
  'TypeScript para desenvolvedores JS': [
    'any vs unknown vs never: quando usar?',
    'Como tipar array de objetos de API?',
    'Union types e type guards na prática?',
    'interface vs type alias?',
    'Generics: exemplo com função reutilizável?',
    'Como configurar tsconfig strict?',
    'Como migrar arquivo .js para .ts aos poucos?',
    'Erros comuns de tipagem em projetos reais?',
  ],
  'Testes com Jest ou Vitest': [
    'Como testar função pura sem mock?',
    'Como mockar módulo importado?',
    'describe, it, expect: estrutura básica?',
    'beforeEach e afterEach: quando usar?',
    'Como testar função async com await?',
    'Snapshot test: quando faz sentido?',
    'Cobertura de código: meta realista?',
    'TDD em JS: por onde começar?',
  ],
  'Node.js essencial (módulos, APIs)': [
    'CommonJS vs ESM no Node: diferença?',
    'Como criar servidor HTTP simples?',
    'fs/promises: ler e escrever arquivo?',
    'Variáveis de ambiente com dotenv?',
    'path.join vs concatenação manual?',
    'O que é event loop no Node?',
    'npm scripts: dev, build, start?',
    'Quando usar Express vs Fastify?',
  ],
  'Debugging e Chrome DevTools': [
    'Breakpoints: como pausar e inspecionar?',
    'Console.log vs debugger: boas práticas?',
    'Como inspecionar Network e falha de API?',
    'Sources: como navegar em código minificado?',
    'Performance tab: identificar gargalo?',
    'Como debugar Promise rejeitada silenciosa?',
    'React DevTools: o que olhar primeiro?',
    'Erros de CORS: como interpretar no console?',
  ],
};
