export const reactQuestions: Record<string, readonly string[]> = {
  'Hooks (useState, useEffect, useContext)': [
    'Qual a diferença entre useState e useRef?',
    'Quando o useEffect é executado e como evitar loop infinito?',
    'Como o useContext ajuda a evitar prop drilling?',
    'Quais são as regras dos Hooks e por que existem?',
    'Como criar um custom hook para reutilizar lógica?',
    'Quando usar useReducer em vez de useState?',
    'O que é stale closure e como evitar em Hooks?',
    'Como funciona o cleanup no return do useEffect?',
  ],
  'Componentes, props e composição': [
    'Como passar dados entre componentes pai e filho com props?',
    'Quando criar um componente novo em vez de repetir JSX?',
    'O que é composição de componentes no React?',
    'Como renderizar listas com key corretamente?',
    'Como organizar uma árvore de componentes em um projeto real?',
    'O que são children e render props?',
    'Como tipar props com TypeScript de forma segura?',
    'Quando usar fragment <> em vez de div?',
  ],
  'Estado global (Context, Redux, Zustand)': [
    'Quando usar estado local vs estado global?',
    'Como o Context API funciona passo a passo?',
    'Redux ou Zustand: qual escolher e por quê?',
    'Como evitar re-renders desnecessários com estado global?',
    'Me dê um fluxo simples de login com estado global.',
    'Como estruturar slices no Redux Toolkit?',
    'O que é middleware e quando usar no Redux?',
    'Como persistir estado (ex.: tema, token) com segurança?',
  ],
  'React Router e data fetching': [
    'Como configurar rotas aninhadas no React Router?',
    'Qual a diferença entre loader e useEffect para buscar dados?',
    'Como proteger rotas que exigem autenticação?',
    'Como passar parâmetros na URL e ler no componente?',
    'Como tratar loading e erro em uma tela de lista?',
    'React Router v6: diferença entre Navigate e redirect?',
    'Como integrar React Query com rotas?',
    'Como fazer prefetch de dados antes de abrir uma tela?',
  ],
  'Performance (memo, useMemo, useCallback)': [
    'Quando usar React.memo de verdade?',
    'Qual a diferença entre useMemo e useCallback?',
    'Como identificar re-render desnecessário?',
    'O que é virtualização de listas e quando usar?',
    'Me mostre um exemplo antes/depois de otimização.',
    'Profiler do React: como usar na prática?',
    'Por que criar função inline no JSX pode ser problema?',
    'Code splitting com lazy e Suspense: como aplicar?',
  ],
  'TypeScript com React': [
    'Como tipar useState com union types?',
    'Como tipar eventos de formulário (ChangeEvent)?',
    'O que é React.FC e devo usar?',
    'Como tipar children e componentes genéricos?',
    'Como tipar props opcionais e valores default?',
    'Como integrar tipos de API com componentes?',
    'type vs interface para props: qual preferir?',
    'Como resolver erros comuns de tipagem no React?',
  ],
  'Testes com React Testing Library': [
    'Qual a diferença entre testar implementação vs comportamento?',
    'Como renderizar um componente e buscar por role/texto?',
    'Como simular clique e digitação do usuário?',
    'Como mockar fetch ou hooks externos?',
    'Como testar componentes com Context?',
    'waitFor e findBy: quando usar cada um?',
    'Como testar rotas com MemoryRouter?',
    'O que deve entrar em um teste de integração de tela?',
  ],
  'Formulários e React Hook Form': [
    'Controlled vs uncontrolled: qual escolher?',
    'Como validar campos com mensagens de erro?',
    'Como usar React Hook Form com Zod?',
    'Como registrar inputs e tratar submit?',
    'Como resetar formulário após sucesso?',
    'Como lidar com campos dinâmicos (array de inputs)?',
    'Como integrar máscara (CPF, telefone) no form?',
    'Acessibilidade em formulários: labels e aria-invalid?',
  ],
  'Next.js e Server Components': [
    'Qual a diferença entre Server e Client Components?',
    'Quando usar "use client" no App Router?',
    'Como buscar dados em Server Components?',
    'O que são Server Actions e quando usar?',
    'Como configurar metadata e SEO por página?',
    'Rotas dinâmicas [id] e catch-all: exemplos?',
    'Como proteger rotas com middleware no Next.js?',
    'Deploy na Vercel: o que revisar antes?',
  ],
  'Acessibilidade (a11y) no React': [
    'O que são roles ARIA e quando usar?',
    'Como tornar botões e links acessíveis por teclado?',
    'Como associar label a input corretamente?',
    'O que é foco visível e por que importa?',
    'Como testar acessibilidade com leitor de tela?',
    'Erros comuns: div clicável sem semântica?',
    'Como fazer modal acessível (focus trap)?',
    'Contraste de cores: como validar no projeto?',
  ],
};
